name: Tennis fun
favicon: null
layout_spectrum: 0.7794790798798203
typography_spectrum: 0.3809292695950717
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7759885038249195
  lightness: 0.6932277546729892
  saturation: 0.4628040187526494
  rhythmicContrast: 0.9207391617819667
purpose: []
